version: '3.8'
services:
  frontend:
    build:
      context: ./datasci-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./datasci-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
